export const AnnotationChart = {
    ActionTypes: {
        INIT_CHART_LOAD: 'INIT_CHART_LOAD',
        INIT_CHART_LOAD_SUCCESS: 'INIT_CHART_LOAD_SUCCESS',
        ON_DIMENSION_CHANGE: 'ON_DIMENSION_CHANGE',
        ON_DIMENSION_CHANGE_SUCSESS:'ON_DIMENSION_CHANGE_SUCSESS',
        ON_TRI_SHAPE_ADDED:'ON_TRI_SHAPE_ADDED',
        ON_TRIANGLE_UPDATE_SUCESS:'ON_TRIANGLE_UPDATE_SUCESS',
        ON_TRI_SHAPE_ACTIVE:'ON_TRI_SHAPE_ACTIVE',
        ON_TRI_SHAPE_ACTIVE_SUCCESS:'ON_TRI_SHAPE_ACTIVE_SUCCESS',
        ON_DRAWING_MODE:'ON_DRAWING_MODE',
        ON_DRAWING_MODE_SUCCESS:'ON_DRAWING_MODE_SUCCESS',
        ON_LINE_ADDED:'ON_LINE_ADDED',
        ON_LINE_UPDATE_SUCESS:'ON_LINE_UPDATE_SUCESS',
        ON_LINE_ACTIVE:'ON_LINE_ACTIVE',
        ON_LINE_ACTIVE_SUCCESS:'ON_LINE_ACTIVE_SUCCESS',
        //on right side click
        ON_CLICK_ACTIVE_SHAPE:'ON_CLICK_ACTIVE_SHAPE',
        ON_CLICK_ACTIVE_SHAPE_SUCCESS:'ON_CLICK_ACTIVE_SHAPE_SUCCESS',
        //Changed based on Layer
        ADD_ANNOTATION_LAYER:'ADD_ANNOTATION_LAYER',
        ADD_ANNOTATION_LAYER_SUCCESS:'ADD_ANNOTATION_LAYER_SUCCESS',
        SET_ANNOTATION_PARENT_LAYER:'SET_ANNOTATION_PARENT_LAYER',
        SET_ANNOTATION_PARENT_LAYER_SUCCESS:'SET_ANNOTATION_PARENT_LAYER_SUCCESS',
        SET_ANNOTATION_TRIANGLES:'SET_ANNOTATION_TRIANGLES',
        SET_ANNOTATION_TRIANGLES_SUCCESS:'SET_ANNOTATION_TRIANGLES_SUCCESS',
        SET_ANNOTATION_RECTANGLES:'SET_ANNOTATION_RECTANGLES',
        SET_ANNOTATION_RECTANGLES_SUCCESS:'SET_ANNOTATION_RECTANGLES_SUCCESS',
        SET_ANNOTATION_CIRCLES:'SET_ANNOTATION_CIRCLES',
        SET_ANNOTATION_CIRCLES_SUCCESS:'SET_ANNOTATION_CIRCLES_SUCCESS',
        SET_ANNOTATION_CHANNELS:'SET_ANNOTATION_CHANNELS',
        SET_ANNOTATION_CHANNELS_SUCCESS:'SET_ANNOTATION_CHANNELS_SUCCESS',
        SET_ANNOTATION_TEXT:'SET_ANNOTATION_TEXT',
        SET_ANNOTATION_TEXT_SUCCESS:'SET_ANNOTATION_TEXT_SUCCESS',
       /*************************/
        SHAPE_ADDED:'SHAPE_ADDED',
        SHAPE_ADDED_SUCCESS:'SHAPE_ADDED_SUCCESS',
        SHAPE_ACTIVE:'SHAPE_ACTIVE',
        SHAPE_ACTIVE_SUCCESS:'SHAPE_ACTIVE_SUCCESS',
        SET_ANNOTATION_ACTIVE_DATA:'SET_ANNOTATION_ACTIVE_DATA',
        SET_ANNOTATION_ACTIVE_DATA_SUCCESS:'SET_ANNOTATION_ACTIVE_DATA_SUCCESS',
        HANDLE_DRAG:'HANDLE_DRAG',

        HANDLE_CLICK: 'HANDLE_CLICK',
        HANDLE_CLICK_SUCCESS:'HANDLE_CLICK_SUCCESS',
    }
};
export const ShapeType={}